### PR TITLE
Fix error

### PR DESCRIPTION
**Pull request by Moini**
Fix error that prevented it from working :/
Could you please merge, Neon22?

### CODE REVIEW

**Comment by Moini** [comment]
Thanks a lot!

**Comment by Moini** [comment]
It's now mentioned here: https://inkscape.org/en/develop/extensions/
Thanks again!

**Comment by Neon22** [comment]
This is the page where I added the extensios i knew about. I thought it was the proper repo.
The other one you indicated (with CSS errros) is it the proper place for all of these ?
http://wiki.inkscape.org/wiki/index.php/Extension_repository

**Comment by Moini** [comment]
Both are good. The more recent one on the web page allows you to add a better presentation, though, and to reach more people, as it's conveniently placed in the Download menu of the main website. 

Developers have been thinking about (some day...) allowing people to install extensions from within Inkscape (and about separating extensions from the main program completely, so they can be updated independently). Having them on the website, in the database already, could pave the way... But those are just my own musings, I don't know what will happen :) - in any case, this will still take a lot of time.

**Comment by Neon22** [comment]
OK. I already have login for the website but I just tried and the page is not editable by me.
I'd be happy to help out getting some of those from the other page up onto the new page.
Specifically the ones that already work with 0.91

How can I help ?

**Comment by Moini** [comment]
For this, you don't need to edit the cms page. The extension gallery is auto-created from all uploaded extensions. 

Just go to your profile, and upload your file from there. Use the 'extension' category, and then it will show up in the extension gallery (takes some time, pages are cached). For adding the thumbnail, you will need to edit the uploaded file, and to use a raster file that is small enough (190px max, I think).

(Arghs, I just noticed we don't have the MIT licence yet to select... I think we should add that very soon. I'll ping Martin Owens about this, and will hopefully add it tomorrow night or so.)

I would like it if we could involve the original authors in keeping the uploaded extensions up-to-date. 

The uploaded files will be associated with the user account of the one who uploads them, so maybe it would be good if we can get them to upload the extensions they maintain themselves in the first place... Do you know any of the other extension authors and could prod them about this?

**Comment by Neon22** [comment]
OK - lets experiment until its sorted out - then I can ping as many inkscape devs as possible with simple instructions on what to do. More chance of success that way :)

**Comment by Neon22** [comment]
E.g. on profile page it prompts me to create my own Gallery. but if I make extensions I'm going to ignore this.
How about instead of:
_Recent Uploads_
- No uploads yet?
  - Visit _your Inkspace_ and create a gallery to start sharing your work with other Inkscape users!

it says:
" Visit your inkscape to add an Extension, Artwork, Tutorials, etc and start sharing your work with other inkscape users."

And on the linked gallery page where it offers "Submit Resource" and "Nothing yet"
it has a line saying:
"Click on Submit Resource to add an Extension, Artwork, Tutorial, Template, etc for use/reference/viewing by other inkscape users."

When adding one - I see that's pretty clear. Nice to add a note that says:
"Extensions can only be released under a subset of licenses to maintain compatibility with Inkscape code."

Also I wonder if its possible to offer completion or somesuch on tags already in use ?

I can't add it yet (license) so will give more feedback. Perhaps I should be doing this on the list ?

Also - you might want to edit your extensions page to indicate at the bottom that this is the method to announce and make available extensions that are created.

**Comment by Moini** [comment]
@Neon22 : Your help with motivating people is very welcome :D

The proposed changes sound like a nice addition to make it more easily understandable, but I can't currently make any code changes myself.

Could you please post them as a bug report / feature request for inkscape-web at https://bugs.launchpad.net/inkscape-web? 
It will be easier to track that way.

The corresponding mailing list is inkscape-docs, if you prefer to discuss there, but the bug report way is probably quicker.

**Pull request merged**
